apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhqiim3y3-nodejs 
  janus-idp.io/tekton: rhqiim3y3-nodejs
  backstage.io/kubernetes-id: rhqiim3y3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhqiim3y3-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  