apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhqiim3y3-nodejs
  janus-idp.io/tekton: rhqiim3y3-nodejs
  backstage.io/kubernetes-id: rhqiim3y3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhqiim3y3-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
